### ISSUE TITLE
Travis does not produce a working snogo binary

### ISSUE THREAD

**Issue by biox** [HealthPartnersOSS/snogo#4]
The produced binary seems to be _way_ too small, must have missed something in the build flags!

**Comment by jmcshane** [comment]
@biox have we ever looked at this? any idea what build flags we need

**Comment by biox** [comment]
A first good step would be disabling CGO during compilation, methinks.

**Comment by biox** [comment]
Check out #6

**Comment by jmcshane** [comment]
Testing release now (needed a new travis API key)

**Comment by biox** [comment]
No such luck

```
./snogo
./snogo: line 1: syntax error near unexpected token `newline'
./snogo: line 1: `!<arch>'
```

I'd have to dig deeper, but I don't have the time right now sadly. Can check on this later tonight if you don't get to it first.

**Comment by jmcshane** [comment]
yeah, i'm checking on it too, my error looks the same:

```
./snogo: line 1: syntax error near unexpected token `newline'
./snogo: line 1: `!<arch>'```

**Comment by jmcshane** [comment]
Fixed it locally and running the build
